name: Detect Secrets Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  detect-secrets:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install detect-secrets
      run: pip install detect-secrets

    - name: Scan for secrets and compare with baseline
      run: |
        cp .secrets.baseline .secrets.baseline.bak
        detect-secrets scan --baseline .secrets.baseline

        grep -v '"generated_at":' .secrets.baseline.bak > before.cleaned
        grep -v '"generated_at":' .secrets.baseline     > after.cleaned

        if ! diff before.cleaned after.cleaned > secrets.diff; then
          echo "::error::Secrets baseline changed (excluding timestamp)."
          cat secrets.diff
          exit 1
        else
          echo "✅ No actual secret changes detected."
        fi
