name: Detect Secrets Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  detect-secrets:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install detect-secrets
      run: pip install detect-secrets

    - name: Scan for secrets and compare with baseline
      run: |
        detect-secrets scan > .secrets.new
        detect-secrets diff .secrets.baseline .secrets.new > secrets.diff || true
        cat secrets.diff
        if [ -s secrets.diff ]; then
          echo "❌ Potential secrets found. Please audit and update your .secrets.baseline"
          exit 1
        else
          echo "✅ No new secrets found."
        fi
